# Generated by Django 4.0.3 on 2022-04-04 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_comment_post_to_comment_alter_profile_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='message',
        ),
    ]
