# Generated by Django 4.0.3 on 2022-04-04 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_post_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_to_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='base.post'),
        ),
    ]
